<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LocalCam.Contracts\LocalCam.Contracts.csproj" />
    <ProjectReference Include="..\..\src\LocalCam.Server\LocalCam.Server.csproj" />
    <ProjectReference Include="..\..\src\LocalCam.Updates\LocalCam.Updates.csproj" />
  </ItemGroup>
</Project>
